### ISSUE TITLE
Create: current status of each player

### ISSUE THREAD

**Issue by LamotheMax** [gugagreen/6441-summer-2015#13]
this includes:

The number of Lantern Cards of each colour held by this player

The value of all Dedication Tokens held by this player (this should be stored separately for each of the three primary types; generic tokens should be counted toward the total for the type they replace)

The number of favor tokens held by this player

Which Lake Tiles the player currently holds (this should be an index into the the data structure which actually describes the deck of available tiles)

**Comment by gugagreen** [comment]
Already done during setup (#2).
