### ISSUE TITLE
Prepare documentation - release 1

### ISSUE THREAD

**Issue by gugagreen** [gugagreen/6441-summer-2015#26]
Prepare documentation: create models (class, erd, state) and explain what is going on and which decisions where taken.

Please use google docs folder that was shared with the team earlier:
https://drive.google.com/folderview?id=0B6wDG0mjgJNEfmNFMnpIX3dEMzlhOURxdC1Yem93UGpmYmlpcERjeXZsMVNXVTZoa09LVFU&usp=sharing

**Comment by LamotheMax** [comment]
File was added to github and to google drive, will remove information about Slick2D for graphical display if not completed for build 1.
