### ISSUE TITLE
Placing a tile on a tile with any side adjacent prevents placement

### ISSUE THREAD

**Issue by LamotheMax** [gugagreen/6441-summer-2015#37]
Play two players.
Place a tile on tile[0] with first player
attempt to place a new tile on first tile (tile[0]) with second player.

This may be a bug in the controller and not in the method, can someone please investigate?

**Comment by gugagreen** [comment]
Example of one attempt to add tile that failed but should have worked (see logs bellow):
Player selects a random tile from his list, then selects one tile from the lake, with one empty spot. Then select sides with empty adjacent both on his tile and the lake tile (i.e., it is a valid placement). But still got the following message:
"The specified place in the lake is occupied by another tile.Hence you can't place your tile at this place".

# LOGS

Alpha has no dedication tokens
The lake currently has the following tiles in it:
0=LakeTile [sides=[TileSide [colour=RED, adjacent=[2-3]], TileSide [colour=WHITE, adjacent=[4-5]], TileSide [colour=BLACK, adjacent=[6-1]], TileSide [colour=BLUE, adjacent=null]], platform=false]
1=LakeTile [sides=[TileSide [colour=ORANGE, adjacent=null], TileSide [colour=ORANGE, adjacent=null], TileSide [colour=BLUE, adjacent=null], TileSide [colour=WHITE, adjacent=[4-6]]], platform=true]
2=LakeTile [sides=[TileSide [colour=BLACK, adjacent=[4-6]], TileSide [colour=PURPLE, adjacent=null], TileSide [colour=PURPLE, adjacent=[3-1]], TileSide [colour=PURPLE, adjacent=null]], platform=false]
3=LakeTile [sides=[TileSide [colour=BLACK, adjacent=[6-1]], TileSide [colour=PURPLE, adjacent=null], TileSide [colour=BLUE, adjacent=null], TileSide [colour=BLUE, adjacent=null]], platform=false]
4=LakeTile [sides=[TileSide [colour=BLACK, adjacent=null], TileSide [colour=BLUE, adjacent=null], TileSide [colour=WHITE, adjacent=[4-6]], TileSide [colour=BLUE, adjacent=null]], platform=true]

---

---

It is player 'Charlie's turn.
You have [0] favors.
You do not have enough favour tokens to make an exchange this turn.
Lantern Card: Lantern [colour=ORANGE, quantity=1]
Lantern Card: Lantern [colour=GREEN, quantity=0]
Lantern Card: Lantern [colour=PURPLE, quantity=2]
Lantern Card: Lantern [colour=WHITE, quantity=1]
Lantern Card: Lantern [colour=BLUE, quantity=1]
Lantern Card: Lantern [colour=RED, quantity=0]
Lantern Card: Lantern [colour=BLACK, quantity=1]
Do you want to make a dedication?
1) Yes
2) No2
2
Now it is time to place a tile.
Lake Tile: 0
    TileSide [colour=WHITE, adjacent=null]
    TileSide [colour=BLACK, adjacent=null]
    TileSide [colour=ORANGE, adjacent=null]
    TileSide [colour=BLACK, adjacent=null]
    Lake Tile 0 does not have a platform
Lake Tile: 1
    TileSide [colour=BLUE, adjacent=null]
    TileSide [colour=RED, adjacent=null]
    TileSide [colour=WHITE, adjacent=null]
    TileSide [colour=BLACK, adjacent=null]
    Lake Tile 1 does not have a platform
Lake Tile: 2
    TileSide [colour=GREEN, adjacent=null]
    TileSide [colour=BLUE, adjacent=null]
    TileSide [colour=ORANGE, adjacent=null]
    TileSide [colour=BLUE, adjacent=null]
    Lake Tile 2 does not have a platform
Select one of your tiles:0
0
Select one of the lake tiles to put your tile next to:
0=LakeTile [sides=[TileSide [colour=RED, adjacent=[2-3]], TileSide [colour=WHITE, adjacent=[4-5]], TileSide [colour=BLACK, adjacent=[6-1]], TileSide [colour=BLUE, adjacent=null]], platform=false]
1=LakeTile [sides=[TileSide [colour=ORANGE, adjacent=null], TileSide [colour=ORANGE, adjacent=null], TileSide [colour=BLUE, adjacent=null], TileSide [colour=WHITE, adjacent=[4-6]]], platform=true]
2=LakeTile [sides=[TileSide [colour=BLACK, adjacent=[4-6]], TileSide [colour=PURPLE, adjacent=null], TileSide [colour=PURPLE, adjacent=[3-1]], TileSide [colour=PURPLE, adjacent=null]], platform=false]
3=LakeTile [sides=[TileSide [colour=BLACK, adjacent=[6-1]], TileSide [colour=PURPLE, adjacent=null], TileSide [colour=BLUE, adjacent=null], TileSide [colour=BLUE, adjacent=null]], platform=false]
4=LakeTile [sides=[TileSide [colour=BLACK, adjacent=null], TileSide [colour=BLUE, adjacent=null], TileSide [colour=WHITE, adjacent=[4-6]], TileSide [colour=BLUE, adjacent=null]], platform=true]
0
0
Select the side of the lake tiles to put your tile next to:
0=TileSide [colour=RED, adjacent=[2-3]]; 1=TileSide [colour=WHITE, adjacent=[4-5]]; 2=TileSide [colour=BLACK, adjacent=[6-1]]; 3=TileSide [colour=BLUE, adjacent=null]; 3
3
Select the side your tile to put next to the lake tile:
0=TileSide [colour=WHITE, adjacent=null]; 1=TileSide [colour=BLACK, adjacent=null]; 2=TileSide [colour=ORANGE, adjacent=null]; 3=TileSide [colour=BLACK, adjacent=null]; 3
3
The specified place in the lake is occupied by another tile.Hence you can't place your tile at this place
