### ISSUE TITLE
Greedy AI Lantern Exchange fails if Lantern stacks are empty

### ISSUE THREAD

**Issue by LamotheMax** [gugagreen/6441-summer-2015#50]
Greedy AI does not check Lantern stack quantity before an exchange and can get an exception if they are empty.
![greedy ai bug](https://cloud.githubusercontent.com/assets/12546918/9230814/7fd05540-40f2-11e5-8898-6ae4aab56be6.PNG)

**Comment by gugagreen** [comment]
fixed
